apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  labels:
    app: frontend
    color: blue
spec:
  replicas: 1
  template:
    metadata:
      name: blue-deploy
      labels:
        app: frontend
        color: blue
    spec:
      containers:
        - image: devopswithcloudhub/python_webpage:purple
          name: blue-deploy
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: frontend
      color: blue